[phases.setup]
nixPkgs = [
  "php82",
  "python311"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "pip3 install -r requirements.txt"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"